name: build-assets

on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM - Cache
        id: npm-cache
        uses: actions/cache@v2
        with:
         path: ~/.npm
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         
      - name: NPM - Install
        run: npm install
      
      - name: NPM - Build
        run: npx mix --production
        
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist --force'
          new_branch: main
          author_name: Webflow Git
          author_email: webflowgit@local
          message: 'Assets built'
